[mypy]
python_version = 3.12
strict = True
warn_return_any = True
warn_unused_ignores = True
disallow_untyped_defs = True
check_untyped_defs = True
no_implicit_optional = True
show_error_codes = True
pretty = True

[mypy-lightgbm.*]
ignore_missing_imports = True

[mypy-shap.*]
ignore_missing_imports = True

[mypy-joblib.*]
ignore_missing_imports = True
